### ISSUE TITLE
bug-free should be 'bug free'

### ISSUE THREAD

**Issue by sebhoss** [matthieubulte/bug-free#1]

**Comment by psysp** [comment]
Should be re-opened, running into the same issue!

**Comment by matthieubulte** [comment]
Did you try switching off and on again?

**Comment by alphec** [comment]
no... actually the bug makes it working for me

**Comment by matthieubulte** [comment]
@alphec built a whole application based on this _bug_.

**Comment by sebhoss** [comment]
can you bring back spacebar heating?
